export const machines = {
    pl: {
        1: {
            model: "ax",
            title: "Stół podnośnikowy HYMO AX",
            text: "Podnośniki hydrauliczne z serii HYMO AX znajdują zastosowanie wszędzie tam, gdzie potrzebne jest łatwe i wygodne niwelowanie różnicy poziomów na stanowiskach pracy. Doskonale sprawdzają się jako wyposażenie stanowisk do pakowania, montażu lub kontroli jakości. W zależności od potrzeb istnieje możliwość odpowiedniego skonfigurowania specyfikacji podnośnika. Stoły nożycowe z serii AX mają udźwig od 500 do 2000 kilogramów, a zakres ich działania dochodzi do wysokości 800 mm. ",
            additionalText: "Platformy hydrauliczne AX mogą być wyposażone w ramę nośną z uchwytami dla wózka widłowego lub paletowego. Daje to możliwość dowolnego przemieszczania ich (bez ładunku) z jednego stanowiska pracy na drugie. Oprócz standardowych modeli, nasze dźwigniki mogą być wyprodukowane w indywidualnie zaprojektowanych rozmiarach, dostosowanych do potrzeb Państwa firmy. Szereg akcesoriów dodatkowych zapewnia pełną elastyczność pracy, czyniąc platformę hydrauliczną wielofunkcyjnym urządzeniem, idealnie dostosowującym się do stawianych mu wymagań. W zależności od potrzeb, platformę podnośnikową można mocować na powierzchni posadzki lub we wgłębieniu. ",
            industries: "Branże",
        },
        2: {
            model: "bx",
            title: "Platforma podnośnikowa HYMO BX",
            text: "Zastosowane modele podnośników hydraulicznych Hymo Maxima technologie to gwarancja ponadprzeciętnej trwałości i wytrzymałości. Wydajne agregaty elektryczno-hydrauliczne oraz wzmocniona konstrukcja urządzeń, umożliwiają zastosowanie ich do pracy ciągłej w linii produkcyjnej. Duży wybór akcesoriów oraz zmiany standardowej konfiguracji Klienta – to wszystko pozwala idealnie dopasować nasze podnośniki do dowolnego środowiska i specyfiki pracy.",
            additionalText: "Platformy podnośne BX przeznaczone wydajnej i ciężkiej pracy w trudnych, niesprzyjających warunkach. Doskonałe zdolności operacyjne, precyzja oraz długa żywotność platform typu BX doskonale sprawdzają się na liniach produkcyjnych w różnych sektorach przemysłu. Ich niezawodność szczególnie cenią sobie firmy z przemysłu motoryzacyjnego. Szeroka gama akcesoriów umożliwia dopasowanie każdego ze stołów do odpowiednich aplikacji. Platformy podnośne BX umożliwiają, w zależności od modelu, podnoszenie ładunków o masie do 3000kg w zakresie wysokości podnoszenia do 1650mm. Wszystkie platformy typu BX posiadają wbudowany pod platformą agregat elektryczno-hydrauliczny.",
            industries: "Branże",
        },
        3: {
            model: "lx",
            title: "Platforma przeładunkowa HYMO LX",
            text: "Zastosowane modele podnośników hydraulicznych Hymo Maxima technologie to gwarancja ponadprzeciętnej trwałości i wytrzymałości. Wydajne agregaty elektryczno-hydrauliczne oraz wzmocniona konstrukcja urządzeń, umożliwiają zastosowanie ich do pracy ciągłej w linii produkcyjnej. Duży wybór akcesoriów oraz zmiany standardowej konfiguracji Klienta – to wszystko pozwala idealnie dopasować nasze podnośniki do dowolnego środowiska i specyfiki pracy.",
            additionalText: "Hymo LX to największy z modeli podnośników z linii Hymo Maxima. Tego typu platformy przeładunkowe są specjalnie zaadaptowane do pracy w ciężkich warunkach, także w przemyśle ciężkim. Dzięki wzmocnionej konstrukcji oraz dodatkowym zabezpieczeniom antykorozyjnym układu napędowego, silników hydraulicznych oraz innych narażonych na wilgoć i mróz elementów modele LX mogą być z powodzeniem instalowane na zewnątrz budynku. Hymo LX idealnie sprawdza się jako platforma przeładunkowa do samochodów ciężarowych. Duża moc idzie w parze z precyzją działania. Rampy przeładunkowe Hymo LX cechują się ładownością do 10 000 kg i wysokością podnoszenia do 1600 mm.",
            industries: "Branże",
            },
        4: {
            model: "dx",
            title: "Podest ruchomy HYMO DX",
            text: "Zastosowane modele podnośników hydraulicznych Hymo Maxima technologie to gwarancja ponadprzeciętnej trwałości i wytrzymałości. Wydajne agregaty elektryczno-hydrauliczne oraz wzmocniona konstrukcja urządzeń, umożliwiają zastosowanie ich do pracy ciągłej w linii produkcyjnej. Duży wybór akcesoriów oraz zmiany standardowej konfiguracji Klienta – to wszystko pozwala idealnie dopasować nasze podnośniki do dowolnego środowiska i specyfiki pracy.",
            additionalText: "HYMO DX znajdują zastosowanie przy podnoszeniu ładunków o ciężarze do 10 000kg i zakresie wysokości podnoszenia do 2000mm. W przypadku, kiedy wymagana jest większa długość platformy, idealnym rozwiązaniem jest wersja DXT, z układem podwójnych nożyc ułożonych horyzontalnie, o udźwigu do 20 000kg. HYMO DX i DXT zostały stworzone aby spełnić wymagania najwyższej ładowności i niezawodności. Podesty ruchome DX i DXT używane są do transportu bardzo ciężkich towarów między poziomami, oraz jako kompletne platformy do ładowania samochodów ciężarowych.",
            industries: "Branże",
            },
        5: {
            model: "bxx",
            title: "Platforma nożycowa HYMO BXX",
            text: "Zastosowane modele podnośników hydraulicznych Hymo Maxima technologie to gwarancja ponadprzeciętnej trwałości i wytrzymałości. Wydajne agregaty elektryczno-hydrauliczne oraz wzmocniona konstrukcja urządzeń, umożliwiają zastosowanie ich do pracy ciągłej w linii produkcyjnej. Duży wybór akcesoriów oraz zmiany standardowej konfiguracji Klienta – to wszystko pozwala idealnie dopasować nasze podnośniki do dowolnego środowiska i specyfiki pracy.",
            additionalText: "Platformy podnośne BXX podobnie jak bliźniacza konstrukcja o modelu BX to urządzenia, które doskonale sprawdzają się przy wykonywaniu trudnych, eksploatujących zadań przy równoczesnym zachowaniu dużej precyzji działania. Urządzenia pracują sprawnie i wydajnie nawet w niesprzyjających warunkach. Długa żywotność i doskonałe parametry techniczne sprawiają, że model BXX idealnie nadaje się jako wsparcie dla linii produkcyjnych praktycznie we wszystkich sektorach przemysłu. Częstym zastosowaniem tego typu podnośników hydraulicznych jest m.in. niwelowanie różnicy poziomów między piętrami hal produkcyjnych. Szeroka gama akcesoriów umożliwia dopasowanie każdego ze stołów do odpowiednich aplikacji. Platformy unoszone BXX przystosowane są do podnoszenia ładunków o masie do 4000kg oraz na wysokości podnoszenia do 4300mm. Podesty ruchome BXX wyposażone są w podwójny lub potrójny system pionowo ułożonych nożyc",
            industries: "Branże",
            },
        6: {
            model: "mxe",
            title: "Stół podnośny HYMO MXE",
            text: "Platformy podnośne z serii MX to sprawdzone i niezawodne urządzenia przeznaczone do szerokiego zakresu zastosowań w większości  gałęzi przemysłu. Ich miejsce jest wszędzie tam, gdzie stawia się na jakość oraz komfort pracy. Każdy z  naszych modeli to przykład na to jak dojrzała, solidna technologia poprawia jakość i ergonomię pracy. Specjalna konstrukcja podnośnika umożliwia opuszczenie do bardzo niskiego poziomu. Dzięki temu towar łatwo i bez żadnych problemów możliwe jest przeprowadzenie procesu załadunku. W ten sposób możemy uniknąć potrzeby podestu hydraulicznego w specjalnie do tego przygotowanym zagłębieniu. To dlatego dźwigniki z serii MX są bardzo mobilne i możliwe jest wykorzystanie ich do wszechstronnych zastosowań.",
            additionalText: "Platformy unoszące serii MX w zależności od specyfikacji oraz modelu mogą podnosić ładunki o wadze dochodzącej nawet do 2000 kg. Ich maksymalna wysokość podnoszenia (wysokość całkowita to wysokość minimalna – po złożeniu + wysokość podnoszenia) wynosi 800 mm. Model MXE to platforma w kształcie litery E. Zastosowane w niej rozwiązania techniczne umożliwiają łatwy załadunek palet za pomocą ręcznego wózka paletowego. Dzięki wspomnianemu już wcześniej niskiemu profilowy platformy, może ona być montowana bezpośrednio na posadce i w razie potrzeby – szybko i łatwo przetransportowana na inne stanowisko pracy.",
            industries: "Branże",
            },
        7: {
            model: "mxr",
            title: "Stół podnośny HYMO MXR",
            text: "Platformy podnośne z serii MX to sprawdzone i niezawodne urządzenia przeznaczone do szerokiego zakresu zastosowań w większości  gałęzi przemysłu. Ich miejsce jest wszędzie tam, gdzie stawia się na jakość oraz komfort pracy. Każdy z  naszych modeli to przykład na to jak dojrzała, solidna technologia poprawia jakość i ergonomię pracy. Specjalna konstrukcja podnośnika umożliwia opuszczenie do bardzo niskiego poziomu. Dzięki temu towar łatwo i bez żadnych problemów możliwe jest przeprowadzenie procesu załadunku. W ten sposób możemy uniknąć potrzeby podestu hydraulicznego w specjalnie do tego przygotowanym zagłębieniu. To dlatego dźwigniki z serii MX są bardzo mobilne i możliwe jest wykorzystanie ich do wszechstronnych zastosowań.",
            additionalText: "Platformy unoszące serii MX w zależności od specyfikacji oraz modelu mogą podnosić ładunki o wadze dochodzącej nawet do 2000 kg. Ich maksymalna wysokość podnoszenia (wysokość całkowita to wysokość minimalna – po złożeniu + wysokość podnoszenia) wynosi 800 mm. Platformy nożycowe typu MXR posiadają prostokątny blat i mogą być ładowane przy pomocy dodatkowej rampy najazdowej (opcja). Podobnie jak model MXT, także MXR mogą być montowane na posadzce lub w zagłębieniu. Również w przypadku tego modelu dla naszych Klientów dostępna jest szeroka gama akcesoriów oraz opcji dodatkowych.",
            industries: "Branże",
            },
        8: {
            model: "txc",
            title: "Wózek podnośnikowy HYMO TXC",
            text: "Model TXC służy przeznaczony jest zarówno do transportowania, jak również do podnoszenia ładunków. Wózki wyposażone są w dwa koła skrętne zapewniające dużą zwrotność i swobodę ruchu. Znajduje zastosowanie jako stanowisko montażowe, platforma do podawania materiałów do maszyn lub też jako wózek służący do przewożenia towarów.",
            additionalText: "Wózki HYMO TCX nie potrzebują zewnętrznego zasilania. Podnoszenie i opuszczanie blatu odbywa się za pomocą dwóch nożnych przycisków. Solidnie wykonane urządzenie, oparte o sprawdzone, stosowane od wielu lat technologie – to gwarancja niezawodności i długowieczności. Hymo TCX produkowane są w czterech  wersjach o udźwigu 150, 300, 350 i 500 kg.",
            industries: "Branże",
            },
        9: {
            model: "mxt",
            title: "Platforma hydrauliczna HYMO MXT",
            text: "Platformy podnośne z serii MX to sprawdzone i niezawodne urządzenia przeznaczone do szerokiego zakresu zastosowań w większości  gałęzi przemysłu. Ich miejsce jest wszędzie tam, gdzie stawia się na jakość oraz komfort pracy. Każdy z  naszych modeli to przykład na to jak dojrzała, solidna technologia poprawia jakość i ergonomię pracy. Specjalna konstrukcja podnośnika umożliwia opuszczenie do bardzo niskiego poziomu. Dzięki temu towar łatwo i bez żadnych problemów możliwe jest przeprowadzenie procesu załadunku. W ten sposób możemy uniknąć potrzeby podestu hydraulicznego w specjalnie do tego przygotowanym zagłębieniu. To dlatego dźwigniki z serii MX są bardzo mobilne i możliwe jest wykorzystanie ich do wszechstronnych zastosowań.",
            additionalText: "Model MXT wyposażony jest w podwójny układ horyzontalnie ułożonych nożyc typu tandem. Zwiększona dzięki temu szerokość blatu oraz moc udźwigu umożliwiają podnoszenie długich, dochodzących do wagi 3000 kg ładunków. Zakres wysokości pracy podnośnika nożycowego to 800 mm. Niski profil stołu podnośnego po jego całkowitym opuszczeniu, w opcjonalnej wersji umożliwia załadunek towaru za pomocą rampy najazdowej. Platformy MXT doskonale nadają się do zakładów produkcyjnych jak również do magazynów. To ekonomiczne rozwiązanie dla firm, które szukają sprzętu spełniającego najwyższe standardy. ",
            industries: "Branże",
            },
        10: {
            model: "axx",
            title: "Platforma nożycowa HYMO AXX",
            text: "Seria stołów podnośnych AXX to nowoczesne, niezawodne urządzenia, których głównym zadaniem jest skuteczne niwelowanie różnicy poziomów w różnego rodzaju środowiskach pracy. Zastosowane w niej rozwiązania techniczne oraz podzespoły są spójne z linią urządzeń AX.  Charakterystyczną cechą tych modeli jest podwójny system  nożyc zastosowanych w układzie pionowym.Standardowe wymiary platformy wynoszą 800 x 600 mm, wysokość podnoszenia jaką osiąga urządzenie to 800 mm. Maksymalna ładowność to 400 kilogramów. Na indywidualne życzenie naszych klientów jesteśmy w stanie dostosować podnośnik do pożądanej konfiguracji zarówno pod względem samych parametrów technicznych urządzenia, jak również zastosowanych w nim akcesoriów dodatkowych. ",
            additionalText: "",
            industries: "Branże",
            },
        marcoTables: {
            model: "marco-tables",
            title: "Stoły podnośnikowe MARCO",
            text: "",
            additionalText: "",
        },
        gruseTables: {
            model: "gruse-tables",
            title: "Stoły podnośnikowe GRUSE",
            text: "",
            additionalText: "",
        },
        customTables: {
            model: "custom-tables",
            title: "Stoły podnośnikowe NA WYMIAR",
            text: "",
            additionalText: "",
        },
    },
    en: {
        1: {
            model: "ax",
            title: "Lift table HYMO AX",
            text: "Hymo AX Lift Tables is available with lifting capacities up to 2000 kg and a stroke of 800 mm. HYMO AX equipped with fork entry base frame (optional accessory) becomes a flexible solution when the movement of the lift between sites, without the load, is required. Hymo AX is an ideal choice.",
            additionalText: "",
            industries: "Branże",
        },
        2: {
            model: "bx",
            title: "Lift table HYMO BX",
            text: "Hymo BX Lift Tables provide the basis of many solutions to industrial lifting problems. They are produced in a range of lift heights and with load capacities from 1 to 3 tons. In tandem format - type BXT - two synchronised tables fixed in line increase the total capacity of 6 tons. Hymo BX tables can be customised for any application. In single, tandem or double configuration, these lift tables can withstand hard operating conditions and are noted for their high operational reliability and long service life.",
            additionalText: "",
            industries: "Branże",
        },
        3: {
            model: "lx",
            title: "Lift table HYMO LX",
            text: "Hymo LX has a lifting capacity up to 10 000 kg and a stroke of up to 1600mm. Hymo LX is designed to meet the demands of high precision and reliability when briding level differences within heavy industry. Hymo LX is specially adapted to loading bay applications and is equipped for external locations. Single unit Capacitiy: 3000 - 10000 kg Lift travel: 1600 - 2000 mm Platform length: 3000 - 3100 mm Platform width: 2000 mm.",
            additionalText: "",
            industries: "Branże",
            },
        4: {
            model: "dx",
            title: "Lift table HYMO DX",
            text: "Hymo DX Lift Tables represent the high-capacity end of the Hymo range offering lifting capacities from 3 to 10 tons. In tandem format - type DXT - two synchronised tables fixed in line increase the total capacity to between 4 and 20 tons and the joint platform is increased proportionately in size. This makes Hymo DX lift tables - in singel or tandem format - often the clear solution for applications with high capacity demands and where some degree of customisation is required. Hymo DX tables are used extensively in materials flow and manufacturing systems, for example in heavy board/sheet feeding and stacking, and coil and reel handling. They are an integral part of production lines - in industries such as automotive manufacturing - and other production-critical process lines. These lift tables also serve as complete loading platforms and as in-plant lifts between floor levels.",
            additionalText: "",
            industries: "Branże",
            },
        5: {
            model: "bxx",
            title: "Lift table HYMO BXX",
            text: "BXX is a double format version of the BX table - two scissor mechanisms are fixed on top of each other. This provides increased lift travel (for use between two floors in a building, for example) with capacities up to 4 tons. Double unit Capacitiy: 1000 - 4000 kg Lift travel: 1500 -4300 mm Platform length: 1350 - 3100 mm Platform width: 800 - 1800 mm Hymo BXXX is an alternative for high lifting heights with the advantage of a rather small platform lenght. A separate power unit is standard.",
            additionalText: "",
            industries: "Branże",
            },
        6: {
            model: "mxe",
            title: "Lift table HYMO MXE",
            text: "Hymo MXE has a lifting capacity up to 2000 kg and a stroke of 800mm. The E-shape platform and the very low closed height makes MXE an unrivalled choice for handling palletised goods. The arms of the 'E' support the pallet. Hymo MXE can be loaded by hand pallet truck. The low closed height means the MXE-table can be sited directly on the floor - no pit is needed. it can quickly and easily be moved to a new location when requred. This lift is for use with open ended pallets. Our E-shaped low-profile table is specially adapted for handling Euro pallets.",
            additionalText: "",
            industries: "Branże",
            },
        7: {
            model: "mxr",
            title: "Lift table HYMO MXR",
            text: "",
            additionalText: "",
            industries: "Branże",
            },
        8: {
            model: "txc",
            title: "Lift trolley HYMO TXC",
            text: "The Hymo Lift Trolley is an all-in-one load transporter and worktable. A mobile lift table, which can be used for the transportation and handling of goods or simply as a workbench for assembly, stacking or machine feeding operations. The TXC lift trolley needs no power supply. The lifting movement is activated with a foot pedal and the lowering with a hand control, allowing the operator to select the most ergonomic working position. Hymo TXC has a lifting cpacity of 150, 300, 350 and 500 kg.",
            additionalText: "",
            industries: "Branże",
            },
        9: {
            model: "mxt",
            title: "Lift table HYMO MXT",
            text: "Hymo MX has a lifting capacity up to 2000 kg and a stroke of 800 mm. Hymo MX has a rectangular platform and can be loaded with the aid of a ramp (option). the MX-table can be placed directly on the floor or in a shallow pit. Hymo MXT has a lifting capacity up to 3000kg and a stroke of 800mm. Hymo MXT has an extra long lifting platform which is faciliated up by two horizontally placed scissor packages. Hymo MXT is designed for the handling of long goods and materials. MXT has a low closed height. They are also ideal as independent workstations handling Euro- and CHEP as wells a UK pallets.",
            additionalText: "",
            industries: "Branże",
            },
        10: {
            model: "axx",
            title: "Lift table HYMO AXX",
            text: "Hymo AXX is a standard model available with a lifting capacity of 400 kg and a stroke of 800mm. Hymo AXX has a vertically mounted double scissors package. Hymo AXX is ideal for handling with 'half-size' pallets (800*600mm).",
            additionalText: "",
            industries: "Branże",
            },
        marcoTables: {
            model: "marco-tables",
            title: "MARCO Lift tables",
            text: "",
            additionalText: "",
        },
        gruseTables: {
            model: "gruse-tables",
            title: "GRUSE Lift tables",
            text: "",
            additionalText: "",
        },
        customTables: {
            model: "custom-tables",
            title: "CUSTOM Lift tables",
            text: "",
            additionalText: "",
        },
    },
  };